### PR TITLE
Helix bindings

### PR DESCRIPTION
**Pull request by Silverquark**

### CODE REVIEW

**Comment by mabasic** [comment]
This is awesome! Great work!

Can we collaborate on this and make it a proper extension?

I am very experienced with TS and have been using Helix for almost a month now :) Love it! These keybindings inside VS Code enable me to have the best of both worlds.

I have noticed some minor differences and a single annoying bug, which I can't figure out how to solve...

`g d` to go to definition. It says `editor.action.revealDefinitionG` not found. But I can't find any mention of `revealDefinition` in the code.

**Comment by mabasic** [comment]
Probably should have cloned the code locally instead of using github search xD.

Thank you for the fix.

Do you have a roadmap of sort?

**Comment by Silverquark** [comment]
That bug should now be fixed!
Feel free to contribute, it would help a lot!

i dont have a roadmap. This was just a thing i built without a proper plan on holiday. 

The base functionality is there, from now on its mostly finding issues and differences to original Helix and fixing them. One issue i know of is that match-sorround with multiple selections on the same line messes up selections.

The original author of Dance has put some work in making Dance compatible with different keymaps. There are still some roadblocks though. In the future this could all live in the original repository.
So this is also a thing that could be worked on.

**Comment by lukepighetti** [comment]
Wasn't sure where to file this: Would be nice to have `C-o` and `C-i` bound to back/forward in VSCode

**Comment by kabouzeid** [comment]
@lukepighetti I've addressed this here: https://github.com/Silverquark/dance/pull/2

**Comment by kabouzeid** [comment]
> I have noticed some minor differences and a single annoying bug, which I can't figure out how to solve...

@mabasic can you elaborate? :)

**Comment by mabasic** [comment]
@kabouzeid 
- pressing x multiple times doesn't expand selection :)

I'm back to helix now. I'll report here the issues as I encounter them because I can't remember now.

**Comment by kabouzeid** [comment]
Alright :) I've already fixed many issues that I've found myself (https://github.com/Silverquark/dance/pull/2).

**Comment by Silverquark** [comment]
> Alright :) I've already fixed many issues that I've found myself (#2).

Sorry for taking so long.

Thanks a lot for the work! I published an update that includes your changes.

**Pull request merged**
